export const LOAD_POKEMON = "LOAD_POKEMON";
export const CAPTURE_POKEMON = "CAPTURE_POKEMON";
export const ADD_TO_TEAM = "ADD_TO_TEAM";
export const RELEASE_POKEMON = "RELEASE_POKEMON";
export const CREATE_BATTLE = "CREATE_BATTLE";
export const MODIFY_BATTLE = "MODIFY_BATTLE";
export const LOAD_INITIAL_TEAM = "LOAD_INITIAL_TEAM";

const actions = {
  LOAD_POKEMON,
  CAPTURE_POKEMON,
  ADD_TO_TEAM,
  RELEASE_POKEMON,
  CREATE_BATTLE,
  MODIFY_BATTLE,
  LOAD_INITIAL_TEAM,
};

export default actions;
